"""initial schema: case library entries and scans

Revision ID: 364da8736679
Revises: 
Create Date: 2026-09-08 13:32:51.630985

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '364da8736679'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_library_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('phrase_or_concept', sa.Text(), nullable=False),
    sa.Column('region', sa.String(length=64), nullable=False),
    sa.Column('category', sa.Enum('linguistic', 'historical', 'brand', 'recent_event', 'imagery', name='risk_category'), nullable=False),
    sa.Column('industry_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('content_type_tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=False),
    sa.Column('date_occurred', sa.Date(), nullable=True),
    sa.Column('severity_baseline', sa.Enum('low', 'medium', 'high', name='severity_level'), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_library_entries_active'), 'case_library_entries', ['active'], unique=False)
    op.create_index(op.f('ix_case_library_entries_category'), 'case_library_entries', ['category'], unique=False)
    op.create_index(op.f('ix_case_library_entries_region'), 'case_library_entries', ['region'], unique=False)
    op.create_table('scans',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('target_markets', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('industry', sa.String(length=128), nullable=False),
    sa.Column('content_type', sa.String(length=128), nullable=False),
    sa.Column('imagery_description', sa.Text(), nullable=True),
    sa.Column('scope_applied', sa.Text(), nullable=False),
    sa.Column('findings', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checked_against_library_version', sa.String(length=32), nullable=False),
    sa.Column('live_search_performed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scans_created_at'), 'scans', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scans_created_at'), table_name='scans')
    op.drop_table('scans')
    op.drop_index(op.f('ix_case_library_entries_region'), table_name='case_library_entries')
    op.drop_index(op.f('ix_case_library_entries_category'), table_name='case_library_entries')
    op.drop_index(op.f('ix_case_library_entries_active'), table_name='case_library_entries')
    op.drop_table('case_library_entries')
    # ### end Alembic commands ###
